# Generated by Django 2.1.2 on 2019-02-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementdetail',
            name='min_veteran',
            field=models.IntegerField(blank=True, null=True, verbose_name='経験者の最低人数'),
        ),
    ]
