# Generated by Django 2.1.2 on 2019-02-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_managementdetail_min_veteran'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.IntegerField(default=1, null=True, verbose_name='必要人数')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Management')),
            ],
        ),
    ]
