# Generated by Django 2.1.2 on 2019-02-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_management_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='part',
            field=models.IntegerField(null=True),
        ),
    ]
