# Generated by Django 2.1.2 on 2019-02-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190207_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='need',
            field=models.IntegerField(null=True),
        ),
    ]
