# Generated by Django 2.1.2 on 2019-02-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_managementneed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='need',
        ),
    ]
