# Generated by Django 2.1.2 on 2019-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_management_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementneed',
            name='part',
            field=models.IntegerField(blank=True, null=True, verbose_name='セクション'),
        ),
    ]
