# Generated by Django 2.1.2 on 2019-02-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190207_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='part',
            field=models.IntegerField(verbose_name='セクション'),
        ),
    ]
