# Generated by Django 2.1.2 on 2019-02-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_managementneed_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementneed',
            name='management',
        ),
        migrations.AddField(
            model_name='managementneed',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementneed',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Department'),
        ),
        migrations.AddField(
            model_name='managementneed',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementneed',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
