# Generated by Django 2.1.2 on 2019-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190227_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementdetail',
            name='reinkin_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='連勤の最大シフト数'),
        ),
    ]
