# Generated by Django 2.1.2 on 2019-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190216_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='hope',
            field=models.IntegerField(blank=True, choices=[(1, '入れる ○'), (2, '入れない ✖︎'), (3, '微妙 ▲')], default=1, verbose_name='希望'),
        ),
    ]
