# Generated by Django 2.1.2 on 2019-02-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190216_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='hope',
            field=models.IntegerField(blank=True, choices=[(1, '入れる ○'), (0, '入れない ✖︎')], default=1, verbose_name='希望'),
        ),
    ]
