# Generated by Django 2.1.2 on 2019-02-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_managementdetail_reinkin_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementdetail',
            old_name='reinkin_max',
            new_name='renkin_max',
        ),
    ]
