# Generated by Django 2.1.2 on 2019-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190217_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='degree',
            field=models.IntegerField(choices=[(0, 'たくさん入れる'), (1, '普通'), (2, '少なめで')], null=True, verbose_name='シフト量の希望'),
        ),
    ]
