# Generated by Django 2.1.2 on 2019-02-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0010_shift_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('degree', models.IntegerField(choices=[(0, 'たくさん入れる'), (1, '普通'), (2, '少なめで')], null=True, verbose_name='シフト量の希望')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='degree',
        ),
    ]
