# Generated by Django 2.1.2 on 2019-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20190321_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementdetail',
            name='max0',
            field=models.IntegerField(blank=True, default=11, null=True, verbose_name='多めに入れる人の最大シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='max1',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='標準の人の最大シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='max2',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='少なめの人の最大シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='min0',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='多めに入れる人の最小シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='min1',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='標準の人の最小シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='min2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='少なめの人の最小シフト数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='min_veteran',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='経験者の最低人数'),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='min_women',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='女性の最低人数'),
        ),
    ]
