# Generated by Django 2.1.2 on 2019-02-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20190224_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='degree',
            field=models.IntegerField(choices=[(0, 'たくさん入れる'), (1, '普通'), (2, '少なめで')], default=1, null=True, verbose_name='シフト量の希望'),
        ),
    ]
