# Generated by Django 2.1.2 on 2019-02-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20190224_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
