# Generated by Django 2.1.2 on 2019-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20190224_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
