# Generated by Django 2.1.2 on 2019-02-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20190224_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Management')),
            ],
        ),
        migrations.AlterField(
            model_name='shiftdetail',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='コメント'),
        ),
    ]
