# Generated by Django 2.1.2 on 2019-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20190224_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementdetail',
            name='max',
        ),
        migrations.RemoveField(
            model_name='managementdetail',
            name='min',
        ),
        migrations.RemoveField(
            model_name='managementdetail',
            name='part',
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='max0',
            field=models.IntegerField(blank=True, null=True, verbose_name='多めに入れる人の最大シフト数'),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='max1',
            field=models.IntegerField(blank=True, null=True, verbose_name='標準の人の最大シフト数'),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='max2',
            field=models.IntegerField(blank=True, null=True, verbose_name='少なめの人の最大シフト数'),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='min0',
            field=models.IntegerField(blank=True, null=True, verbose_name='多めに入れる人の最小シフト数'),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='min1',
            field=models.IntegerField(blank=True, null=True, verbose_name='標準の人の最小シフト数'),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='min2',
            field=models.IntegerField(blank=True, null=True, verbose_name='少なめの人の最小シフト数'),
        ),
    ]
