# Generated by Django 2.1.2 on 2019-02-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20190224_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementdetail',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementdetail',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementdetail',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Department'),
        ),
    ]
