# Generated by Django 2.1.2 on 2019-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_auto_20190224_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementdetail',
            name='min_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='女性の最低人数'),
        ),
    ]
